### ISSUE TITLE
Deploy to IBM Cloud fails

### ISSUE THREAD

**Issue by scottdangelo** [IBM/customer-churn-prediction#16]
The deploy to IBM cloud  button fails:
```
Staging...
None of the buildpacks detected a compatible application
Exit status 222
Staging failed: STG: Exited with status 222
Stopping instance c5de5965-ba3c-40d8-a1c6-443f01c739a6
Destroying container
Successfully destroyed container

FAILED
Error restarting application: NoAppDetectedError
			
TIP: Buildpacks are detected when the "cf push" is executed from within the directory that contains the app source code.

Use 'cf buildpacks' to see a list of supported buildpacks.

Use 'cf logs sda-customer-churn-prediction-2-9-28 --recent' for more in depth log information.

Finished: FAILED
```

**Comment by HebaNAS** [comment]
@scottdangelo, there may be multiple reasons for that:

1. You should try running this command after cd-ing into the frontend folder. This has been written in the readme

2. If you're inside the frontend folder, then probably the app name need to be changed in the manifest.yml, as this route will be taken since I deployed the app with that name already. I added this to the readme

3. I moved a piece of code in `server/server.js` from the global scope to the scope inside the `/results` route as this failed on app deployment for the first time. The issue was that the app is looking for services bound and their secrets in the environment. On first deployment no services are bound yet and this fails. I already have instructions in the readme on how to connect the needed services to the app after deploying to the cloud.

I tried all this on a fresh clone of the repo, it should be working. I'm creating a pull request with the needed changes.

Also, on a different note, I don't have access anymore to my enterprise github account, so I won't be able to view messages and comments there.

**Comment by scottdangelo** [comment]
I am still getting the same error. I will look into this today.

**Comment by scottdangelo** [comment]
I've fixed this in PR #19
